### ISSUE TITLE
这个可以放到base里面吗

### ISSUE THREAD

**Issue by HuangJAndroid** [yangchaojiang/DemoLoadView#3]
new LoadViewHelper(((ViewGroup)findViewById(android.R.id.content)).getChildAt(0))
当activity里面有fragment的话就崩
有什么方法吗

**Comment by yangchaojiang** [comment]
不能哦
需要在fragment加父类布局

**Comment by HuangJAndroid** [comment]
在网络请求的onerror方法写了showerror 。为什么没网第一次进去是显示error，点击重试就一直是loading，但是onerror方法也走了

**Comment by yangchaojiang** [comment]
好的，谢谢你的反馈，请求的onerror（） 也调用showerror 页面没有更换是吧。

**Comment by HuangJAndroid** [comment]
没有

**Comment by HuangJAndroid** [comment]
有没有解决的方法

**Comment by yangchaojiang** [comment]
有的哦，有问题一天左右处理，并更新版本

**Comment by HuangJAndroid** [comment]
解决了请告诉我一下哦，谢谢

**Comment by yangchaojiang** [comment]
我会通知你😊

**Comment by yangchaojiang** [comment]
对了，你有操作截图或者gif 动图

**Comment by yangchaojiang** [comment]
我没有复现出来，白天有工作，所以晚上

**Comment by HuangJAndroid** [comment]
![Uploading bug2.jpg…]()
log的3和4之间是showerror    第一次进去有打印也是显示加载失败，然后点击重试，有打印但一直是显示加载中的布局

**Comment by HuangJAndroid** [comment]
图片上传不了。
就是在网络请求的onerror方法里showerror， 断网第一次进去是显示加载失败，然后点击重试，但一直是显示加载中的布局，两次都一定走了这方法

**Comment by HuangJAndroid** [comment]
showerror有什么条件吗

**Comment by yangchaojiang** [comment]
没有哦

**Comment by HuangJAndroid** [comment]
那就奇怪了

**Comment by yangchaojiang** [comment]
我仔细排查一下

**Comment by yangchaojiang** [comment]
还是没有浮现出来。😂😂😂 这就尴尬

**Comment by HuangJAndroid** [comment]
好吧

**Comment by HuangJAndroid** [comment]
真是奇怪，两次走的什么都一样，也都进了showError(null, null);。偏偏第二次就是一直停留在加载中

**Comment by yangchaojiang** [comment]
方便 使用库的代码，。看一下么 整个流程

**Comment by yangchaojiang** [comment]
你的代码

**Comment by HuangJAndroid** [comment]
if (loadEmpty == null) {
}
这个去掉了就好了，但是点击重试，没有加载中了

**Comment by HuangJAndroid** [comment]
if (loadError == null) {

**Comment by yangchaojiang** [comment]
你是不是使用自定义状态 showerror(null,null); 自定义使用哦   showerror(); 默认的

**Comment by HuangJAndroid** [comment]
application里面是没写


我就是直接调helper.showError()

**Comment by yangchaojiang** [comment]
还是看看你的代码。可以Q1007181167

**Comment by kona5362** [comment]
同样遇到这个问题了 = =  重试button点击后 在Rxjava 的onError里helper.showError()还是显示之前的loading界面

**Comment by yangchaojiang** [comment]
好的，我检查检查一下 @kona5362

**Comment by yangchaojiang** [comment]
1.1.2 完美解决@ @HuangJAndroid
