### ISSUE TITLE
反复执行导致显示异常的问题

### ISSUE THREAD

**Issue by kona5362** [yangchaojiang/DemoLoadView#4]
项目中点击重试按钮后一直卡在loading界面
用下面这段代码测试了下
发现最后一个应该显示error界面，实际却显示loading界面了。
        mLoadViewHelper = new LoadViewHelper(mViewPager);
        mLoadViewHelper.showLoading();
        mLoadViewHelper.showError("加载失败","重试");
        mLoadViewHelper.showLoading();
        mLoadViewHelper.showError("加载失败","重试");
        mLoadViewHelper.showLoading();
        mLoadViewHelper.showError("加载失败","重试");
瞅了下源码没理解，哈哈，望解惑。

**Comment by yangchaojiang** [comment]
😂   你着操作，，，

**Comment by kona5362** [comment]
那测试代码。
实际情况是这样的....
mLoadViewHelper.setListener(new OnLoadViewListener() {
            @Override
            public void onRetryClick() {
                requestData();
            }
        });
requestData();
....
public void requestData(){
mLoadViewHelper.showLoading();
....
                   ......Observable.....
                   @Override
                    public void onError(@NonNull Throwable e) {
                        mLoadViewHelper.showError("加载失败","重试");
                    }
}


没网时候，会线loading，然后显示error界面。此时点击重试，就一直显示loading了。
debug发现最后的确是执行的 mLoadViewHelper.showError("加载失败","重试");

**Comment by yangchaojiang** [comment]
版本1.1.1

**Comment by kona5362** [comment]
厉害了大神

**Comment by yangchaojiang** [comment]
没有问题了吧

**Comment by kona5362** [comment]
重试后还是在一直Loading..... 0.0  尴尬了

**Comment by yangchaojiang** [comment]
，，，，

**Comment by yangchaojiang** [comment]
你确定第二次public void onError(@nonnull Throwable e) {} rx 回调了。
我记得 rx onError（）回调一次,  就不会在回调   要 重新订阅才会回调。

**Comment by kona5362** [comment]
的确是重新订阅了  0.0
这是requestData()完整代码

private void requestData() {
        mLoadViewHelper.showLoading("加载中...");
        DiscoverApi discoverApi = RetrofitHelper.getInstance().createApi(DiscoverApi.class);
        Observable<DiscoverColumn> discoverColumnObservable = discoverApi.requestDiscoverColumn();
        discoverColumnObservable
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Observer<DiscoverColumn>() {
                    @Override
                    public void onSubscribe(@NonNull Disposable d) {
                    }
                    @Override
                    public void onNext(@NonNull DiscoverColumn discoverColumn) {
                        int code = discoverColumn.getCode();
                        if (code >= 200 && code < 300) {
                            initTabLayout(discoverColumn.getData());
                            mLoadViewHelper.showContent();
                        }else{
                            mLoadViewHelper.showError("加载失败","重试");
                        }
                    }
                    @Override
                    public void onError(@NonNull Throwable e) {
                        mLoadViewHelper.showError("加载失败","重试");
                    }
                    @Override
                    public void onComplete() {
                    }
                });
    }

**Comment by kona5362** [comment]
流程简化一下就是如下代码了
mLoadViewHelper.setListener(new OnLoadViewListener() {
@override
public void onRetryClick() {
requestData();
}
});
requestData();
....
private void requestData(){
        mLoadViewHelper.showLoading("加载中...");
        mLoadViewHelper.showError("加载失败","重试");
}

**Comment by yangchaojiang** [comment]
测了两个小时，还是没有测试出来。调用 showError（）肯定显示 @kona5362 。你有没有二次封装什么？

**Comment by kona5362** [comment]
没有封装过，新建了个demo项目如下
点击重试后还是一直旋转

public class MainActivity extends AppCompatActivity {

    private LoadViewHelper mLoadViewHelper;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        LinearLayout llGroup = findViewById(R.id.ll_group);

        mLoadViewHelper = new LoadViewHelper(llGroup);
        mLoadViewHelper.showLoading();
        mLoadViewHelper.showError();
        mLoadViewHelper.setListener(new OnLoadViewListener() {
            @Override
            public void onRetryClick() {
                mLoadViewHelper.showLoading();
                mLoadViewHelper.showError();
            }
        });
    }
}

**Comment by kona5362** [comment]
布局文件：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.kona.apitest.MainActivity">
    <LinearLayout
        android:id="@+id/ll_group"
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="Hello World!"/>
    </LinearLayout>
</LinearLayout>

**Comment by kona5362** [comment]
布局文件
![image](https://user-images.githubusercontent.com/28619342/33748370-1b818808-dc03-11e7-9316-c98de69fc914.png)

**Comment by yangchaojiang** [comment]
原来如此

**Comment by kona5362** [comment]
0.0 难道发现了什么不得了的事情

**Comment by yangchaojiang** [comment]
![image](https://user-images.githubusercontent.com/13806413/33749964-d1649a68-dc0b-11e7-8d0c-9767d2e20dfa.png)
 dao按道理来讲，1.1.1版本已经处理了。

**Comment by kona5362** [comment]
确实是compile 'com.ycjiang:loadviewhelper:1.1.1'

第一次的    
mLoadViewHelper.showLoading();
mLoadViewHelper.showError();
是正常的

不正常的是点击事件里面的。就是点击重试后会一直显示loading页面，而不是展示error页面
 mLoadViewHelper.setListener(new OnLoadViewListener() {
        @Override
        public void onRetryClick() {
            mLoadViewHelper.showLoading();
            mLoadViewHelper.showError();   //点击重试后，最后执行的应该这行，但是界面显示的还是loading界面
        }
    });

**Comment by yangchaojiang** [comment]
新建了个demo项目发我一下。，我Q1007181167
